name: Release

on:
    push:
        branches:
            - 'master'

jobs:
    create-release:
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        runs-on: ubuntu-18.04

        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: false

            - name: Semantic Release
              env:
                  GITHUB_TOKEN: ${{ secrets.APIGITHUB }}
              run: npx -p @semantic-release/git -p semantic-release semantic-release
